packages:
  - 'packages/**'
  - 'examples/**'
  - 'scripts'
overrides:
  "@polkadot/api-augment": "16.5.6"
  "@polkadot/api": "16.5.6"
  "@polkadot/apps-config": "0.170.1"
  "@polkadot/types": "16.5.6"
  "@polkadot/util-crypto": "14.0.3"
  "@polkadot/util": "14.0.3"
  "axios": ">=1.15.1"
  "esbuild": ">=0.28.1"
  "form-data": ">=4.0.6"
  "handlebars": ">=4.7.9"
  "postcss": ">=8.5.10"
  "uuid": ">=11.1.1"
  "vite": ">=8.0.16"
  "ws": ">=8.21.0"
  "js-yaml": ">=4.1.2"
linkWorkspacePackages: true
preferWorkspacePackages: true
allowBuilds:
  bufferutil: false
  es5-ext: false
  esbuild: true
  lefthook: true
  utf-8-validate: false
