import { MoonChain } from '../interfaces';

export enum MoonChainKey {
  MoonbaseAlpha = 'MoonbaseAlpha',
  Moonbeam = 'Moonbeam',
  Moonriver = 'Moonriver',
}
export const MOON_CHAINS: Record<MoonChainKey, MoonChain> = {
  [MoonChainKey.MoonbaseAlpha]: {
    key: MoonChainKey.MoonbaseAlpha,
    name: 'Moonbase Alpha',
    ws: 'wss://wss.api.moonbase.moonbeam.network',
    parachainId: 1000,
    decimals: 18,
    chainId: 1287,
    unitsPerSecond: 50_000_000_000_000_000n,
    weights: {
      descendOriginWeight: 9_620_000n,
      withdrawAssetWeight: 200_000_000n,
      buyExecutionWeight: 130_464_000n + 100_000_000n,
      transactWeight: 31_693_000n + 25_000_000n,
    },
  },
  [MoonChainKey.Moonbeam]: {
    key: MoonChainKey.Moonbeam,
    name: 'Moonbeam',
    ws: 'wss://wss.api.moonbeam.network',
    parachainId: 2004,
    decimals: 18,
    chainId: 1284,
    unitsPerSecond: 10_000_000_000_000_000_000n,
  },
  [MoonChainKey.Moonriver]: {
    key: MoonChainKey.Moonriver,
    name: 'Moonriver',
    ws: 'wss://wss.api.moonriver.moonbeam.network',
    parachainId: 2023,
    decimals: 18,
    chainId: 1285,
    unitsPerSecond: 100_000_000_000_000_000n,
  },
};

export enum ChainKey {
  Acala = 'Acala',
  AlphanetRelay = 'AlphanetRelay',
  Astar = 'Astar',
  Bifrost = 'Bifrost',
  BitCountryPioneer = 'BitCountryPioneer',
  BifrostPolkadot = 'BifrostPolkadot',
  Calamari = 'Calamari',
  Crab = 'Crab',
  CrustShadow = 'CrustShadow',
  Darwinia = 'Darwinia',
  DarwiniaPangoro = 'DarwiniaPangoro',
  Equilibrium = 'Equilibrium',
  EquilibriumAlphanet = 'EquilibriumAlphanet',
  HydraDX = 'HydraDX',
  Integritee = 'Integritee',
  Interlay = 'Interlay',
  Karura = 'Karura',
  Khala = 'Khala',
  Kintsugi = 'Kintsugi',
  Kusama = 'Kusama',
  LitentryAlphanet = 'LitentryAlphanet',
  Litmus = 'Litmus',
  MoonbaseBeta = 'MoonbaseBeta',
  Parallel = 'Parallel',
  ParallelHeiko = 'ParallelHeiko',
  Phala = 'Phala',
  Polkadot = 'Polkadot',
  Robonomics = 'Robonomics',
  Shiden = 'Shiden',
  Statemine = 'Statemine',
  StatemineAlphanet = 'StatemineAlphanet',
  Statemint = 'Statemint',
  UniqueAlpha = 'UniqueAlpha',
}
