name: Debug Changeset Bot

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          corepack enable # Required if using pnpm
          pnpm install || yarn install || npm install

      - name: List directory structure
        run: |
          echo "Repository root structure:"
          ls -la
          echo "Packages directory structure:"
          tree -L 2

      - name: Show workspace packages
        run: |
          echo "Checking workspaces:"
          pnpm list --depth=1 || yarn workspaces list || npm ls --depth=1

      - name: Show Changeset Status
        run: |
          echo "Checking Changeset Status:"
          npx changeset status --verbose
